//   https://api.krcg.org/card_search Post='crypt'


const krcgCrypt = [
    "Aabbt Kindred",
    "Aaron Bathurst",
    "Aaron Duggan, Cameron's Toady",
    "Abd al-Rashid",
    "Abdelsobek",
    "Abebe",
    "Abid bin Haji, Scholar of Mirrors",
    "Abiku",
    "Abu Nuwasi",
    "Accorri Giovanni",
    "Adana de Sforza",
    "Adelaide Davis",
    "Adhiambo",
    "Adonai",
    "Adri, The Seeker",
    "Adrianne",
    "Aeron",
    "Afifa, The Herald",
    "Agaitas, The Scholar of Antiquities",
    "Agatha",
    "Agrippina",
    "Agru Kabera",
    "Ahmose Chambers",
    "Aidan Lyle",
    "Aimee Laroux",
    "Aimery Methuin",
    "Aisata Swanou",
    "Aisha",
    "Aisha az-Zahra",
    "Aisling Sturbridge",
    "Aiyana, The Wolfcatcher",
    "Akram",
    "Aksinya Daclau",
    "Al-Ashrad, Amr of Alamut",
    "Al-Ashrad, Amr of Alamut (ADV)",
    "Al-Muntaquim, The Avenger",
    "Al-Muntathir, God's Witness",
    "Alabástrom",
    "Alan Sovereign",
    "Alan Sovereign (ADV)",
    "Alcoan",
    "Aleister Crowley",
    "Alejandro Aguirre",
    "Aleph",
    "Alessandro Garcia",
    "Alex Camille",
    "Alex Wilkins",
    "Alexa Draper",
    "Alexander Silverson",
    "Alexandra",
    "Alexis Sorokin",
    "Alfred Benezri",
    "Alfred Benezri (ADV)",
    "Ali Kar",
    "Alice Chen",
    "Alicia Barrows",
    "Alicia Cortez",
    "Allanyan Serata",
    "Allison Maller",
    "Allonzo Montoya",
    "Almiro Suarez",
    "Almodo Giovanni",
    "Alonso Petrodon",
    "Alonzo Guillen",
    "Alu",
    "Alvaro, The Scion of Angelica",
    "Amadeo",
    "Amaravati",
    "Amavi",
    "Amber",
    "Ambrogino Giovanni",
    "Ambrogino Giovanni (ADV)",
    "Ambrosio Luis Monçada, Plenipotentiary",
    "Amelia",
    "Amelia, The Blood Red Tears",
    "Amenophobis",
    "America Johnson",
    "Amisa",
    "Ana Rita Montaña",
    "Anarch Convert",
    "Anastasia Grey",
    "Anastasz di Zagreb",
    "Anatole, Prophet of Gehenna",
    "Andi Liu",
    "Andre LeRoux",
    "Andrea Giovanni",
    "Andreas, The Bard of Crete",
    "Andrei Puxon",
    "Andrew Emory",
    "Andrew Stuart",
    "André the Manipulator",
    "Andy",
    "Angel",
    "Angel Chavarria",
    "Angela Decker",
    "Angela Preston",
    "Angelica, The Canonicus",
    "Angelique",
    "Angelo",
    "Angus the Unruled",
    "Anisa Marianna Lopez",
    "Anjalika Underwood",
    "Anka, Priestess of Thorns",
    "Ankh-sen-Sutekh",
    "Ankla Hotep",
    "Anna \"Dictatrix11\" Suljic",
    "Annabelle Triabell",
    "Annazir",
    "Anne-Marie Bourgeois, Inconnu Recruiter",
    "Anneke",
    "Anson",
    "Antara",
    "Antoine, The Lost",
    "Antoinette DuChamp",
    "Antoinette Dubois",
    "Antoinette, She Who Watches",
    "Anton",
    "Antonino",
    "Antonio Delgado",
    "Antonio Veradas",
    "Antonio d'Erlette",
    "Antón de Concepción",
    "Anu Diptinatpa",
    "Anvil",
    "Anwar",
    "Apache Jones",
    "Apolonia Czarnecki",
    "Appius Claudius Corvus",
    "Appolonius",
    "Appolonius (ADV)",
    "Ardan Lane",
    "Aredhel",
    "Aren, Priest of Eshu",
    "Ariadne",
    "Ariane",
    "Arianne, The Conqueror",
    "Ariel",
    "Arika",
    "Arishat",
    "Aristotle de Laurent",
    "Armin Brenner",
    "Arnold Simpson",
    "Arnulf Jormungandrsson",
    "Arriette Sylla",
    "Art Morgan",
    "Artemis",
    "Arthur Denholm",
    "Asguresh",
    "Ash Harrison",
    "Ashlesha",
    "Ashley",
    "Assad Salhoum",
    "Astrid Thomas",
    "Augustus Giovanni",
    "Aunt Linda",
    "Aurora Van Brande, Paladin",
    "Axel Von Anders",
    "Ayelea, The Manipulator",
    "Ayelech",
    "Ayo Igoli",
    "Azaneal",
    "Aziz, Dammar of Istanbul",
    "Azrael",
    "Baba Yaga, the Iron Hag",
    "Babalawo Alafin",
    "Badger",
    "Badr al-Budur",
    "Badr, Shadow of Granada",
    "Baixinho",
    "Bajazet al-Nasir",
    "Bakr",
    "Baldesar Rossellini",
    "Banjoko",
    "Barbaro Lucchese",
    "Baron Dieudonne",
    "Baroque",
    "Barry",
    "Barth",
    "Bartholomew",
    "Basil",
    "Basilia",
    "Basir",
    "Batsheva",
    "Batsheva (ADV)",
    "Bear Paw",
    "Beast, The Leatherface of Detroit",
    "Beauregard Krueller",
    "Beckett",
    "Beckett (ADV)",
    "Beetleman",
    "Bela",
    "Bela Kardoza",
    "Belinde",
    "Belle Equitone",
    "Benedict Giovanni, Agent",
    "Benedito, a Lanterna",
    "Benjamin Rose",
    "Bernard, the Scourge",
    "Bertrand d'Anjou",
    "Beth Malcolm",
    "Bethany Ray",
    "Bez Dunsirn",
    "Bianca",
    "Bill Butler",
    "Billy",
    "Bindusara, Historian of the Kindred",
    "Bituin",
    "Black Annis",
    "Black Cat",
    "Black Lotus",
    "Black Wallace",
    "Blackhorse Tanner",
    "Blaise",
    "Blanche Hill",
    "Blister",
    "Bloodfeud",
    "Bloody Mary",
    "Blythe Candeleria",
    "Bobby Lemon",
    "Bolesław Gutowski",
    "Boss Callihan",
    "Boss Callihan (ADV)",
    "Bothwell",
    "Boy Toy",
    "Brachah",
    "Brazil",
    "Bret Stryker",
    "Brian Thompson",
    "Brigitte Mandisa",
    "Brock Sterling",
    "Bronwen",
    "Brooke",
    "Bruce de Guy",
    "Brunhilde",
    "Brunhilde (ADV)",
    "Bryan Van Duesen",
    "Bulscu",
    "Bulscu (ADV)",
    "Bupe Kuila",
    "Byzar",
    "Béatrice \"Oracle171\" Tremblay",
    "Béatrice L'Angou",
    "C.J.",
    "Cagliostro, The Grand Copht",
    "Cailean",
    "Caitlin",
    "Calebos",
    "Calebros, The Martyr",
    "Caliban",
    "Callirus",
    "Calvin Cleaver",
    "Cameron",
    "Camille Devereux, The Raven",
    "Cao Nguyen",
    "Cardano",
    "Carlak",
    "Carlotta Giovanni",
    "Carmen",
    "Carmine Giovanni",
    "Carna, The Princess Witch",
    "Carolina Vález",
    "Caroline Bishops",
    "Carter",
    "Casey Snyder",
    "Casino Reeds",
    "Cassandra Langely, The Waif",
    "Cassandra, Magus Prime",
    "Castiel",
    "Catalina Vega",
    "Catherine du Bois",
    "Cedric",
    "Celine Chevalier",
    "Cesewayo",
    "Cesewayo (ADV)",
    "Chalcedony",
    "Chandler Hungerford",
    "Charice Fontaigne",
    "Charles Delmare",
    "Charlie Tyne",
    "Chas Giovanni Tello",
    "Chaundice",
    "Chavi Oraczko",
    "Chelsea Blake",
    "Chester DuBois",
    "Christanius Lionel, The Mad Chronicler",
    "Christine Boscacci",
    "Christopher Houghton",
    "Chrysanthemum",
    "Cicatriz",
    "Clarissa Steinburgen",
    "Claudia",
    "Claudio Severino",
    "Claudio Severino (ADV)",
    "Claus Wegener",
    "Claven",
    "Clea Auguste d'Holford",
    "Clifton Derrik",
    "Cock Robin",
    "Cohn Rose",
    "Colette",
    "Colin Flynn",
    "Conchita Morales",
    "Conrad Adoula",
    "Constanza Vinti",
    "Corine Marcón",
    "Cornelius Ottavio",
    "Count Germaine",
    "Count Germaine (ADV)",
    "Count Jocalo",
    "Count Ormonde",
    "Count Vladimir Rustovitch",
    "Count Zaroff",
    "Courtland Leighton",
    "Creamy Jade",
    "Cristobal Ghiberti",
    "Cristofero Giovanni",
    "Cristos Mantigo",
    "Crow",
    "Crusher",
    "Cybele",
    "Cynthia Ingold",
    "Cyscek",
    "Céleste Lamontagne",
    "Céleste, The Voice of a Secret",
    "César Holfield",
    "Daliah",
    "Daliyah",
    "Damaskenos, Herald of Leandro",
    "Dame Hollerton",
    "Dan Murdock",
    "Dancin' Dana",
    "Dancin' Dana (ADV)",
    "Dani",
    "Danielle Diron",
    "Danielle Diron (ADV)",
    "Danny Larkshill",
    "Danylo",
    "Darius Styx",
    "Dark Selina",
    "Darlene Killian",
    "Darrell Boyce, Consul",
    "Darva Felispa",
    "Darvag, The Butcher of Rus",
    "David Morgan, The Scourge",
    "De Sade",
    "DeSalle",
    "Dedefra",
    "Dela Eden",
    "Delilah Easton",
    "Delilah Monroe",
    "Delizbieta of the Dark Eyes",
    "Demdemeh",
    "Demetrius Slater",
    "Democritus",
    "Denette Stensen",
    "Desiree Narayan, Anarch Historian",
    "Devin Bisley",
    "Devyn",
    "Dhita Choudhair",
    "Diana Vick",
    "Didi Meyers",
    "Diego Giovanni",
    "Dieter Kleist",
    "Dimple",
    "Dirk",
    "Djuhah, The Bronze Bow",
    "Dmitra Ilyanova",
    "Dmitri Borodin",
    "Doctor Streck",
    "Dodd",
    "Dolie",
    "Dollface",
    "Dolphin Black",
    "Domenic Giovanni",
    "Dominique",
    "Dominique (ADV)",
    "Dominique Santo Paulo",
    "Don Caravelli",
    "Don Cerro",
    "Don Cruez, The Idealist",
    "Don Michael Antonio Giovanni",
    "Donald Cargill",
    "Donatello Giovanni",
    "Donatien",
    "Donny Kowalczyk",
    "Dorian Strack",
    "Doris McMillon",
    "Dorka",
    "Dovey Ebfwe",
    "Doyle Fincher",
    "Dr. Allan Woodstock",
    "Dr. Douglas Netchurch",
    "Dr. Jest",
    "Dr. John Casey",
    "Dr. John Dee",
    "Dr. Julius Sutphen",
    "Dr. Julius Sutphen (ADV)",
    "Dr. Lawrence Mayhew",
    "Dr. Morrow, The Skindoctor",
    "Dr. Oliver Genet",
    "Dr. Solomon Grey",
    "Dr. Stephen Norton",
    "Dr. Sutton Gassaway",
    "Dragos",
    "Dre, Leader of the Cold Dawn",
    "Droescher One-Eye",
    "Drozodny",
    "Drusilla Euphemia",
    "Duality",
    "Duck",
    "Durga Syn",
    "Dylan",
    "Dylan (ADV)",
    "Dónal O'Connor",
    "Earl",
    "Earl \"Shaka74\" Deams",
    "Ebanezer Roush",
    "Echo",
    "Eddie Gaines",
    "Edith Blount",
    "Edward Neally",
    "Edward Vignes",
    "Effie Lowery",
    "Egothha",
    "Ehrich Weiss",
    "Elena Gutierrez",
    "Elena Mendoza Vasquez",
    "Elihu",
    "Elimelech the Twice-Damned",
    "Eliott Sinclair, Virtuoso Thespian",
    "Elisabetta Romano",
    "Elizabeth Conde",
    "Elizabeth Dimitros",
    "Elizabeth Westcott",
    "Ellen Fence, the Tracker",
    "Ellison Humboldt",
    "Ember Wright",
    "Emerson Bridges",
    "Emerson Wilkershire III",
    "Emily Carson",
    "Enam",
    "Enid Blount",
    "Enkidu, The Noah",
    "Enzo Giovanni, Pentex Board of Directors",
    "Enzo Giovanni, Pentex Board of Directors (ADV)",
    "Epikasta Rigatos",
    "Erebus",
    "Eric Kressida",
    "Eric Milliner",
    "Erichtho",
    "Erick \"Shophet125\" Franco",
    "Erinyi",
    "Erlik",
    "Ermenegildo, The Rake",
    "Esau",
    "Esoara",
    "Ethan Locke",
    "Etrius",
    "Eugene",
    "Eugenio Estevez",
    "Eurayle Gelasia Mylonas",
    "Evan Klein",
    "Evan Rogers",
    "Evangeline",
    "Evil Jensen",
    "Eze, The Demon Prince",
    "Ezekiel, Lord of Montreal",
    "Ezmerelda",
    "Ezra Hawthorne",
    "Fabrizia Contreraz",
    "Fahd al-Zawba'a",
    "Fairuza",
    "Fakir al Sidi",
    "Falhu Shibaba",
    "Faruq",
    "Father Juan Carlos",
    "Fatima al-Faqadi",
    "Federico di Padua",
    "Felicia Mostrom",
    "Feo Ramos",
    "Fergus Alexander",
    "Ferox, The Rock Lord",
    "Ferox, The Rock Lord (ADV)",
    "Fida'i",
    "Fidus, The Shrunken Beast",
    "Fish",
    "Flavia, Avenging Angel",
    "Fleurdumal",
    "Florentina Lengauer",
    "Flávio Gonçalves",
    "Fode Kourouma",
    "Foureyes",
    "Francesca Giovanni",
    "Francis Milliner",
    "Francisco Domingo de Polonia",
    "Franciscus",
    "Frank Litzpar",
    "Frank Weisshadel",
    "François \"Warden\" Loehr",
    "François Villon",
    "Freddy Gage",
    "Frederick the Weak",
    "Frondator",
    "Frère Marc",
    "Fustuk",
    "Gabi",
    "Gabriel de Cambrai",
    "Gabrielle di Righetti",
    "Gabrin",
    "Ganesh",
    "Ganhuru",
    "Garret",
    "Gaspare Giovanni",
    "Gatjil Munyarryun",
    "Gavrylo",
    "Gaël Pilet",
    "Gelasia Fotiou",
    "Gem Ghastly",
    "Gemini",
    "General Perfidio Díos",
    "Genevieve",
    "Gengis",
    "Gengis (ADV)",
    "Genina, The Red Poet",
    "Gentha Shale",
    "George Frederick",
    "Gerald FitzGerald",
    "Gerald Windham",
    "Gerard",
    "Gerard Rafin",
    "Gharston Roland",
    "Ghede",
    "Ghivran Dalaal, The Dead God",
    "Giangaleazzo, The Traitor",
    "Gianmaria Giovanni",
    "Gideon Fontaine",
    "Gilbert Duane",
    "Gillespi Giovanni",
    "Gillian Krader",
    "Giotto Verducci",
    "Giovanni del Georgio",
    "Gisela Harden, The Winnower",
    "Gitane St. Claire",
    "Giuliano Vincenzi",
    "Gloria Giovanni",
    "Glycon",
    "Gold Pan Dan",
    "Goratrix",
    "Goratrix (ADV)",
    "Gotsdam, The Tired Warrior",
    "Gracetius",
    "Gracis Nostinus",
    "Graham Gottesman",
    "Gratiano",
    "Gravitnir",
    "Greensleeves",
    "Greer Worder",
    "Greger Anderssen",
    "Grendel the Worm-Eaten",
    "Greta Kircher",
    "Grimgroth",
    "Grotesque",
    "Gualtiero Ghiberti",
    "Guedado",
    "Guggenheim",
    "Guido Lucciano",
    "Guillaume Giovanni",
    "Guillermo Arsuaga",
    "Gunnar",
    "Gunther, Beast Lord",
    "Gustaphe Brunnelle",
    "Gustav Breidenstein",
    "Gustav Mallenhous",
    "Gustavo Morales",
    "Gwen Brand",
    "Gwendolyn",
    "Gwendolyn Fleming",
    "Gwyedd",
    "Haakon Mortensen",
    "Hadrian Garrick",
    "Hafsa, The Watcher",
    "Hagar Stone",
    "Halim Bey",
    "Hamid Mansour",
    "Handsome Dan",
    "Hanna Redmonds",
    "Hannibal",
    "Hannibal (ADV)",
    "Hannigan",
    "Hardestadt",
    "Harika Guljan",
    "Harlan Graves",
    "Harold Tanner",
    "Harold Zettler, Pentex Director",
    "Harrod",
    "Harry Reese",
    "Hartmut Stover",
    "Hasani",
    "Hasina Kesi",
    "Hazimel",
    "Heather Florent, The Opportunist",
    "Hecate",
    "Hector Sosa",
    "Hector Trelane",
    "Heinrick Schlempt",
    "Hektor",
    "Helen Fairchild",
    "Helena",
    "Helena (ADV)",
    "Helena Casimir",
    "Henri Lavenant",
    "Henry Taylor",
    "Herbert Westin",
    "Hermana Hambrienta Mayor",
    "Hermana Hambrienta Menor",
    "Hesha Ruhadze",
    "Hester Reed",
    "Hezekiah Rutledge",
    "High Priest Angra Mainyu",
    "Hillanvale",
    "Hiram \"Hide\" DeVries",
    "Homa",
    "Honest Abe",
    "Honorine Ateba",
    "Horace Radcliffe",
    "Horatio",
    "Horatio Ballard",
    "Horrock",
    "Horst von Brühl",
    "Howler",
    "Hrothulf",
    "Huang, Blood Cultist",
    "Hugo",
    "Huitzilopochtli",
    "Hukros",
    "Humo",
    "Husamettin",
    "Iago Castille",
    "Ian Forestal",
    "Ian Wallingford",
    "Ibn Khaldun, Scholar",
    "Icarus, The Manchurian",
    "Idalia, Prophet of Guadalajara",
    "Idrissa",
    "Ignacio, The Black Priest",
    "Ignatius",
    "Ignazio Giovanni",
    "Igo the Hungry",
    "Iliana",
    "Ilias cel Frumos",
    "Ilse",
    "Ilyana Ravidovich",
    "Imanna",
    "Imogen",
    "Inez \"Nurse216\" Villagrande",
    "Ingram Frizer",
    "Ingrid Rossler",
    "Ingrid Russo",
    "Iniko, The Black Lion",
    "Intisar",
    "Inyanga",
    "Inês Tristão",
    "Ira Rivers",
    "Irena",
    "Iris Bennett",
    "Isabel Giovanni",
    "Isabel de Leon",
    "Isanwayen",
    "Ismitta",
    "Isouda de Blaise",
    "Itzahk Levine",
    "Ivan Krenyenko",
    "Ivan Krenyenko (ADV)",
    "Izhim abd Azrael",
    "J. Oswald \"Ozzy\" Hyde-White",
    "Jack",
    "Jack \"Hannibal137\" Harmon",
    "Jack Dawson",
    "Jack Dawson (ADV)",
    "Jack Drake",
    "Jack Tredegar",
    "Jackie",
    "Jacko",
    "Jackson Asher",
    "Jacob Bragg",
    "Jacob Fermor",
    "Jacob, The Glitch",
    "Jacques Molay",
    "Jacques Rouge",
    "Jaggedy Andy",
    "Jalal Sayad",
    "Jalan-Aajav",
    "Jamal",
    "Jan Pieterzoon",
    "Jan Pieterzoon (ADV)",
    "Jane Sims",
    "Janet Langer",
    "Janey Pickman",
    "Janine",
    "Jann Berger",
    "Janni",
    "Jara Drory",
    "Jaroslav Pascek",
    "Jason, The World's Voice",
    "Javier Montoya",
    "Javier Montoya (ADV)",
    "Jayakumar",
    "Jayne Jonestown",
    "Jazz Wentworth",
    "Jean Lisle",
    "Jefferson Foster",
    "Jeffrey Mullins",
    "Jenna Cross",
    "Jennie \"Cassie247\" Orne",
    "Jennifer \"Flame61\" Vidisania",
    "Jephta Hester",
    "Jeremiah Noble",
    "Jeremy \"Wix\" Wyzchovsky",
    "Jeremy MacNeil",
    "Jeremy MacNeil (ADV)",
    "Jeremy Talbot",
    "Jerry",
    "Jesse Menks",
    "Jessica",
    "Jessica (ADV)",
    "Jesús Alcalá",
    "Jezebelle",
    "Jibade el-Bahrawi",
    "Jibade el-Bahrawi (ADV)",
    "Jimmy Dunn",
    "Jing Wei",
    "Joaquin Murietta",
    "Joaquina Amaya",
    "Joe \"Boot\" Hill",
    "Johan Wrede",
    "Johann Matheson",
    "Johannes Castelein",
    "Johannes Worringen",
    "John \"Cop90\" O'Malley",
    "John Paleologus",
    "Jonathan Gursel",
    "Jorge De La Muerte, The Agent",
    "Josef",
    "Josef von Bauren",
    "Joseph Cambridge",
    "Joseph DiGiaccomo",
    "Joseph Fischer",
    "Joseph O'Grady",
    "Josette",
    "Joshua Tarnopolski",
    "Jost Werner",
    "Jozz",
    "João Bilé",
    "Juan Cali",
    "Juanita Santiago",
    "Jubal",
    "Judah",
    "Juggler",
    "Julia Prima",
    "Julian Sanders",
    "Julio Martinez",
    "Julius",
    "Juniper",
    "Justine Chen, Innocent",
    "Justine, Elder of Dallas",
    "Kabede Maru",
    "Kahina the Sorceress",
    "Kai Simmons",
    "Kalila",
    "Kalinda",
    "Kallista, Master Sculptor",
    "Kamaria",
    "Kamau Jafari",
    "Kamiri wa Itherero",
    "Kamiri wa Itherero (ADV)",
    "Kanimana Belghazi",
    "Kanya Akhtar",
    "Karen Suadela",
    "Karif al Numair",
    "Karl",
    "Karmenita Yoryari",
    "Karsh",
    "Karsh (ADV)",
    "Kashan",
    "Kassiym Malikhair",
    "Katarina",
    "Katarina Kornfeld",
    "Kateline Nadasdy",
    "Katherine Stoddard",
    "Kathy Glens",
    "Kay Polerno",
    "Kazimir Savostin",
    "Keith Moody",
    "Keller Thiel",
    "Kemintiri",
    "Kemintiri (ADV)",
    "Kendrick",
    "Kenyatta",
    "Kephamos, High Priest of Marrakech",
    "Kervos, The Lieutenant",
    "Kestrelle Hayes",
    "Khalid",
    "Khalil Anvari",
    "Khalil Ravana",
    "Khalu",
    "Khay'tall, Snake of Eden",
    "Khurshid",
    "Kij Dansky",
    "Kiradin",
    "Kisha Bhimji",
    "Kite",
    "Klaus Konrecht",
    "Klaus van der Veken",
    "KoKo",
    "Konrad Fleischer",
    "Korah",
    "Kostantin, Baro of the Caravan",
    "Krassimir",
    "Krid",
    "Kurt Densch",
    "Kurt Strauss",
    "Kyle Strathcona, Cardinal of Canada",
    "Kyoko Shinsegawa",
    "Kyrylo",
    "L'Épuisette",
    "La Viuda Blanca",
    "Lachlan, Noddist",
    "Ladislas Toth, The Torch",
    "Lady Constancia",
    "Lady Vadislava",
    "Lady Zara Slatikov",
    "Laecanus",
    "Laika",
    "Lailah",
    "Lalitha",
    "Lambach",
    "Lambach (ADV)",
    "Lana Butcher",
    "Langa",
    "Larissa Moreira",
    "Larry",
    "Laszlo Mirac",
    "Laura Goldman",
    "Lauren",
    "Laurent de Valois",
    "Layla bint-Nadr",
    "Lazarus",
    "Lazarus (ADV)",
    "Lazarus James",
    "Lazverinus, Thrall of Lambach",
    "Le Dinh Tho",
    "Leaf \"Potter116\" Pankowski",
    "Leandro",
    "Lectora",
    "Legba",
    "Leila Monroe",
    "Len Konopka",
    "Lena Rowe",
    "Lenny Burkhead",
    "Leo Washington",
    "Leon",
    "Lernean",
    "Leumeah",
    "Lia Milliner",
    "Lille Haake",
    "Lillian",
    "Lin Jun",
    "Lindsay Yates",
    "Lisa Noble",
    "Lisandro Giovanni",
    "Lisette Vizquel",
    "Lisé",
    "Lithrac",
    "Little Tailor of Prague",
    "Little Willie",
    "Liz \"Ticket312\" Thornton",
    "Lizette",
    "Lloyd Brooks",
    "Lodin (Olaf Holte)",
    "Lolita",
    "Lolita Houston",
    "Loonar",
    "Lord Aaron Wesley Wilkshire",
    "Lord Ashton",
    "Lord Ephraim Wainwright",
    "Lord Fianna",
    "Lord Leopold Valdemar",
    "Lord Tremere",
    "Lord Vauxhall",
    "Lorenzo Detuono",
    "Lorrie Dunsirn",
    "Louhi",
    "Louis Fortier",
    "Louis Fortier (ADV)",
    "Louis de Maisonneuve",
    "Luanda Magere",
    "Lubomira Hradok",
    "Luc",
    "Luca Italicus",
    "Lucas Halton",
    "Luccia Paciola",
    "Lucian",
    "Lucian, the Perfect",
    "Lucina",
    "Lucinde, Alastor",
    "Lucita",
    "Lucita (ADV)",
    "Lucretia, Cess Queen",
    "Lucubratio",
    "Lucy Markowitz",
    "Ludmijla Rakoczy",
    "Lukas",
    "Luke Fellows",
    "Lula Burch",
    "Luma, Stone Beauty",
    "Lumumba",
    "Luna Giovanni",
    "Lupe \"Cabbie22\" Droin",
    "Lupo",
    "Lupo Giovanni",
    "Luther",
    "Lutz von Hohenzollern",
    "Lydia Van Cuelen",
    "Lydia, Grand Praetor",
    "Lynn Thompson",
    "Lázár Dobrescu",
    "MacAlister Marshall",
    "Macoute",
    "Madame Guil",
    "Madeleine Giovanni",
    "Madison",
    "Magdelena Schaefer",
    "Makarios, The Seducer",
    "Malabranca",
    "Malachai",
    "Malcolm",
    "Maldavis",
    "Maldavis (ADV)",
    "Malgorzata",
    "Mamadou Keita",
    "Maman Boumba",
    "Mambo Jeanne",
    "Marcel de Breau",
    "Marcellus",
    "March Halcyon",
    "Marcia Felicia Licinia",
    "Marciana Giovanni, Investigator",
    "Marconius",
    "Marcus Vitel",
    "Marcus Vitel (ADV)",
    "Margaret Milliner",
    "Margarite",
    "Marge Khan",
    "Marguerite Foccart",
    "Marguerite Foccart (ADV)",
    "Maria Stone",
    "Maria Stone (ADV)",
    "Mariana Gilbert",
    "Marianna",
    "Mariano Pomposo",
    "Marie Faucigny",
    "Marie-Pierre",
    "Mariel St. John",
    "Mariel, Lady Thunder",
    "Marino Reymundo Vásquez",
    "Mario Giovanni",
    "Marion \"Teacher193\" Perks",
    "Marion French",
    "Maris Streck",
    "Mark",
    "Mark Decker",
    "Marla Kenyon",
    "Marlena",
    "Marlene, The Infernalist",
    "Marta",
    "Marthe Dizier",
    "Martin Franckel",
    "Martino della Passaglia",
    "Marty Lechtansi",
    "Mary Anne Blaire",
    "Mary Johnson",
    "Mary the Black",
    "Masdela",
    "Masika",
    "Masika (ADV)",
    "Masika St. John",
    "Maskini",
    "Massassi",
    "Massimo Falconi",
    "Mata Hari",
    "Matasuntha",
    "Matata",
    "Mateusz Gryzbowsky",
    "Mateusz Kazimirski, Biker of Blood",
    "Matteus, Flesh Sculptor",
    "Matthew",
    "Matthew Romans",
    "Matthias",
    "Maureen, Dark Priestess",
    "Max Lowell",
    "Maxwell",
    "Mazz",
    "Meaghan",
    "Melek",
    "Melinda Galbraith",
    "Melinda Galbraith (ADV)",
    "Melisande",
    "Melissa Barton",
    "Menele",
    "Menele (ADV)",
    "Meno Ngari",
    "Mercy, Knight Inquisitor",
    "Merrill Molitor",
    "Meshenka",
    "Michael Luther",
    "Michael diCarlo",
    "Michaela",
    "Mictlantecuhtli",
    "Midget",
    "Miguel Cordovera",
    "Miguel Santo Domingo",
    "Mikael Birkholm",
    "Miller Delmardigan, Teacher of Bahari",
    "Milo, The Invisible Horror",
    "Mimir",
    "Min-seo",
    "Mina Grotius",
    "Miranda Sanova",
    "Mirembe Kabbada",
    "Miriam Benyona",
    "Misrak",
    "Missy Shillingford",
    "Mister Schwartz",
    "Mistress Fanchon",
    "Mitchell, The Headhunter",
    "Mithras",
    "Mitru the Hunter",
    "Mkhokheli",
    "Monica Chang",
    "Monique",
    "Monique Kim",
    "Montano",
    "Montecalme",
    "Monty Coven",
    "Mordechai Ben-Nun",
    "Morel",
    "Morlock",
    "Morrow the Sage",
    "Mosfair",
    "Mouse",
    "Mowgli",
    "Mr. Noir",
    "Muaziz, Archon of Ulugh Beg",
    "Mugur Sabau",
    "Muhandis",
    "Muhsin Samir",
    "Mukhtar Bey",
    "Murat",
    "Muricia",
    "Muriel Foucade",
    "Muse",
    "Mustafa Rahman",
    "Mustafa, The Heir",
    "Myrna Goldman",
    "Mélusine d'Anjou",
    "Nadima",
    "Nahir",
    "Nahum Enosh",
    "Nails",
    "Nakhthorheb",
    "Nakova, Advocate of Golconda",
    "Nana Buruku",
    "Nangila Were",
    "Naomi Stewart",
    "Nassir",
    "Natalia",
    "Natasha Volfchek",
    "Navar McClaren",
    "Nedal, The Careless",
    "Neel Ramanathan",
    "Nefertiti",
    "Nefertiti (ADV)",
    "Neferu",
    "Nehemiah",
    "Nehsi",
    "Neighbor John",
    "Nepata",
    "Nergal",
    "Nergal (ADV)",
    "Nestor Kaba",
    "Nettie Hale",
    "New Blood",
    "Ngozi Ekwensu",
    "Nichodemus",
    "Nicholas Chang",
    "Nickolai, The Survivor",
    "Nicomedes",
    "Nigel the Shunned",
    "Nik",
    "Nik Sikko",
    "Nikolaus Vermeulen",
    "Nitidas",
    "Nizzam al-Latif",
    "Nkechi",
    "Nkule Galadima",
    "Normal",
    "Nostoket",
    "Nu, The Pillar",
    "Nunzio Giovanni",
    "Nuriel",
    "Obaluaye",
    "Obsidian",
    "Ogwon",
    "Ohanna",
    "Old Neddacka",
    "Olga Triminov",
    "Oliver Thrace",
    "Olivia",
    "Olugbenga",
    "Omaya",
    "Omer",
    "Omme Enberbenight",
    "Onaedo",
    "Ondine \"Boudicca\" Sinclair",
    "Orlando Oriundus",
    "Oshri Dahan",
    "Osric Vladislav",
    "Otieno",
    "Owain Evans, The Wanderer",
    "Ox, Viceroy of the Hollows",
    "Ozmo",
    "Panagos Levidis",
    "Panya, The Wicked",
    "Paolo Sardenzo",
    "Papa Legba",
    "Pariah",
    "Parmenides",
    "Parnassus",
    "Patrick",
    "Patrik Söderberg",
    "Patrizia Giovanni, Collector of Secrets",
    "Paul \"Sixofswords29\" Moreton",
    "Paul Calderone",
    "Paul Cordwood",
    "Paul DiCarlo, The Alpha",
    "Paul Forrest, False Prophet",
    "Paulo de Castille",
    "Pavlo",
    "Pearl",
    "Pedrag Hasek",
    "Pedro Cortez",
    "Pentweret",
    "Percival",
    "Persephone Tar-Anis",
    "Persia, The Beautiful Statue",
    "Petaniqua",
    "Petaniqua (ADV)",
    "Peter \"Outback295\" Rophail",
    "Peter Blaine",
    "Petra",
    "Petru Sipos",
    "Phaedyme",
    "Phagian",
    "Pherydima",
    "Philip van Vermeer IV",
    "Philippe de Marseilles",
    "Phillipe Rigaud",
    "Pieter",
    "Pieter van Dorn",
    "Piotr Andreikov",
    "Pochtli",
    "Polly Kay Fisher",
    "Porphyrion",
    "Porphyry",
    "Portia",
    "Prejudice",
    "Preston Varrick",
    "Primo Giovanni",
    "Pug Jackson",
    "Pugfar",
    "Qadir ul-Ghani",
    "Qawiyya el-Ghaduba",
    "Queen Anne",
    "Quentin",
    "Quentin King III",
    "Quentin King III (ADV)",
    "Qufur am-Heru",
    "Quincy, The Trapper",
    "Quinton McDonnell",
    "Quira, The Bitch Queen",
    "Rabbat, The Sewer Goddess",
    "Rachel Brandywine",
    "Radeyah",
    "Radu Bistri",
    "Rafael de Corazon",
    "Rafaele Giovanni",
    "Raful al-Zarqa",
    "Rain",
    "Rake",
    "Ramiel DuPre",
    "Ramiro",
    "Ramona",
    "Ramona (ADV)",
    "Randall",
    "Randel, The Coward",
    "Ranjan Rishi, Camarilla Scholar",
    "Ransam, The Old Man",
    "Raphael Catarari",
    "Raphaela Giovanni",
    "Rashid Stockton",
    "Rashiel",
    "Rathmere",
    "Raziya Samater",
    "Rebekah",
    "Rebekka, Chantry Elder of Munich",
    "Redbone McCray",
    "Reg Driscoll",
    "Regilio, The Seeker of Akhenaten",
    "Regina Giovanni, The Right Hand of Augustus",
    "Reginald Moore",
    "Reiner Stoschka",
    "Remilliard, Devout Crusader",
    "Renenet",
    "Reverend Adams",
    "Reverend Adams (ADV)",
    "Reverend Blackwood",
    "Reverend Djoser Jones",
    "Rex, The Necronomist",
    "Reza Fatir, The Dark Angel",
    "Richard Tauber, Ayelea's Puppet",
    "Richter, The Templar of Du Mont",
    "Ricki Van Demsi",
    "Rico Loco",
    "Rigby, Crusade Vanguard",
    "Righteous Endeavor",
    "Robert Price",
    "Robin Withers",
    "Rocia",
    "Roderick Phillips March",
    "Rodolfo",
    "Rodrigo",
    "Roger Farnsworth",
    "Roland Bishop",
    "Roland Loussarian",
    "Roman Alexander",
    "Roreca Quaid",
    "Rosa Hernández",
    "Rosa Martínez",
    "Rosalina Cortez",
    "Rosemarie",
    "Roxanne, Rectrix of the 13th Floor",
    "Royce",
    "Rudolfo Giovanni",
    "Rufina Soledad",
    "Rurik Rakoczy",
    "Rusticus",
    "Ruth McGinley",
    "Rutor",
    "Ruxandra",
    "Ryan",
    "Ryder",
    "Ryszard",
    "Sabine Lafitte",
    "Sabrina",
    "Sadie",
    "Sahana",
    "Sahira Siraj",
    "Saiz",
    "Sajid al Misbah",
    "Salbatore Bokkengro",
    "Salinger",
    "Salvador Garcia",
    "Salvatore Giovanni",
    "Samantha",
    "Samat Ramal-Ra, Archon",
    "Sammy",
    "Samson",
    "Sandra White",
    "Sanjay Chakrabarti",
    "Sanjo",
    "Santaleous",
    "Saqqaf, Keeper of the Grand Temple of Set",
    "Sarah Brando",
    "Sarah Cobbler",
    "Sarah Raines",
    "Sargon",
    "Sarisha Veliku",
    "Sarrasine",
    "Sarrasine (ADV)",
    "Sascha Vykos, The Angel of Caine",
    "Sascha Vykos, The Angel of Caine (ADV)",
    "Sasha Miklos",
    "Saul Meira",
    "Saulot, The Wanderer",
    "Saxum, Master of Slaves",
    "Sayshila",
    "Scarlet Carson O'Toole",
    "Schuyler",
    "Scout Youngwood",
    "Sean Andrews",
    "Sean Rycek",
    "Sebastian Marley",
    "Sela",
    "Sela (ADV)",
    "Selena",
    "Selma the Repugnant",
    "Sennadurek",
    "Sennuwy, The Promoter",
    "Seren Sukardi",
    "Serenna the White",
    "Sergei Voshkov, The Eye",
    "Servius Marius Pustula",
    "Seterpenre",
    "Sha-Ennu",
    "Shaggydog",
    "Shahara al-Rashwa",
    "Shahid",
    "Shalmath",
    "Shane Grimald",
    "Shannon Price, the Whisperer",
    "Shasa Abu Badr",
    "Shawnda Dorrit",
    "Sheela Na Gig",
    "Sheila Mezarin",
    "Sheldon, Lord of the Clog",
    "Shemti",
    "Sheva Carr",
    "Shiloh Marie, Vengeance",
    "Sigrid Bekker",
    "Silas",
    "Silvia Giovanni",
    "Sir Henry Johnson",
    "Sir Marriot D'Urban",
    "Sir Ralph Hamilton",
    "Sir Walter Nash",
    "Sisocharis",
    "Sister Evelyn",
    "Skidmark",
    "Skryta Zyleta",
    "Skulk",
    "Slag",
    "Smallpox Griet",
    "Smash",
    "Smudge the Ignored",
    "Sobayifa",
    "Socrate Cidibe",
    "Soldat",
    "Solomon Batanea",
    "Sonja Blue",
    "Sophia Watson",
    "Spider",
    "Spider-Killer",
    "Spiridonas",
    "Spleen, Georgio Gutterpunk",
    "Stanislava",
    "Stavros",
    "Stefano Giovanni",
    "Stephen Bateson",
    "Stephen Milliner",
    "Steve Booth",
    "Stick",
    "Stravinsky",
    "Strohmann",
    "Styles Margs",
    "Suhailah",
    "Sukainah",
    "Sully",
    "Sundervere, The Devil Brahmin",
    "Sundown",
    "Sundown (ADV)",
    "Sutekh, The Dark God",
    "Suzanne Kadim",
    "Sybren van Oosten",
    "Sylvester Simms",
    "Sylvie Helgon",
    "Synesios",
    "Synner-G",
    "Szechenyi Jolán, Mother of Horrors",
    "Sébastien Goulet",
    "Sébastien Goulet (ADV)",
    "T.J.",
    "Tabitha Fisk",
    "Talbot",
    "Talley, The Hound",
    "Tammy Walenski",
    "Tamoszius",
    "Tanginé",
    "Tansu Bekir",
    "Tara",
    "Tarautas",
    "Tarbaby Jack",
    "Tariq, The Silent",
    "Tariq, The Silent (ADV)",
    "Tarrence Moore",
    "Tatiana Romanov",
    "Tatiana Stepanova, Alastor",
    "Tatu Sawosa",
    "Tayshawn Kearns",
    "Tears, The Dark Pierrot",
    "Tegyrius, Vizier",
    "Tegyrius, Vizier (ADV)",
    "Teresita, The Godmother",
    "Tereza Rostas",
    "Terrell Harding",
    "Terrence",
    "Terrifisto",
    "Terry",
    "The Ankou",
    "The Arcadian",
    "The Baron",
    "The Capuchin",
    "The Colonel",
    "The Dowager",
    "The Dracon",
    "The Horde",
    "The Kikiyaon",
    "The Medic",
    "The Rose",
    "The Siamese",
    "The unnamed",
    "Thelonius",
    "Themistocles",
    "Theo Bell",
    "Theo Bell (ADV)",
    "Theron",
    "Thetmes, Caliph of Alamut",
    "Thomas De Lutrius",
    "Thomas Steed, The Angry",
    "Thomas Thorne",
    "Thomasso Ghiberti",
    "Thucimia",
    "Tiberius, The Scandalmonger",
    "Timothy Crowley",
    "Titi Camara",
    "Titus Camille",
    "Tobias Smith",
    "Toby",
    "Tock",
    "Tom",
    "Tomaine",
    "Tommy",
    "Tony",
    "Topaz",
    "Tori Longwood",
    "Torvus Bloodbeard",
    "Toy",
    "Travis \"Traveler72\" Miller",
    "Trevon Parker",
    "Troglodytia",
    "Troius",
    "Truman",
    "Tryphosa",
    "Tsigane",
    "Tsunda",
    "Tupdog",
    "Tura Vaughn",
    "Tusk, The Talebearer",
    "Tusk, The Talebearer (ADV)",
    "Tyler",
    "Tyler McGill",
    "Ubende",
    "Ublo-Satha",
    "Uchenna",
    "Ugadja",
    "Ulrike Rothbart",
    "Ulugh Beg, The Watcher",
    "Uma Hatch",
    "Umdava",
    "Una",
    "Uncle George",
    "Undele",
    "Unmada",
    "Unre, Keeper of Golgotha",
    "Ur-Shulgi, The Shepherd",
    "Urenna Bunu",
    "Uriah Winter",
    "Uriel",
    "Urraca",
    "Uta Kovacs",
    "Uzoma",
    "Vaclav Petalengro",
    "Valerius Maior, Hell's Fool",
    "Valerius Maior, Hell's Fool (ADV)",
    "Valkyrie",
    "Valois Sang, The Watcher",
    "Vanessa",
    "Vardar Vardarian",
    "Vasantasena",
    "Vasilis, The Traitor of Don Cruez",
    "Vasiliy Vasilevich",
    "Vasily",
    "Vassily Taltos",
    "Vedel Esbreno",
    "Veejay Vinod",
    "Velya, The Flayer",
    "Venere Carboni",
    "Verbruch",
    "Vestgeir",
    "Victor Donaldson",
    "Victor Gerard",
    "Victor Pelletier",
    "Victor Revell, Loyalist",
    "Victor Tolliver",
    "Victoria",
    "Victoria Ash",
    "Victorine Lafourcade",
    "Vidal Jarbeaux",
    "Viktor, The Night General",
    "Vincent Day, Paladin and Paragon",
    "Violet Tremain",
    "Violette Prentiss",
    "Virgil",
    "Virginie, Prodigy",
    "Viri",
    "Virstania, The Great Mother",
    "Vittorio Giovanni",
    "Vlad Tepes",
    "Vliam Andor",
    "Volker, The Puppet Prince",
    "Volo",
    "Vulture",
    "Wah Chun-Yuen",
    "Walker Grimes",
    "Wamukota",
    "Watenda",
    "Wauneka",
    "Weirich Waldburg",
    "Wendy Wade",
    "White Lily",
    "Wilhelm Waldburg",
    "William Biltmore",
    "William Thorbecke",
    "Winterlich",
    "Wise Frog",
    "Wolf Valentine",
    "Wolfgang",
    "Wren",
    "Wynn",
    "Xaviar",
    "Xaviar (ADV)",
    "Xendil Charmer",
    "Xeper, Sultan of Lepers",
    "Xian \"DziDzat155\" Quan",
    "Xipe Totec",
    "Yasmin the Black",
    "Yavu Matebo",
    "Yazid Tamari",
    "Yazid Tamari (ADV)",
    "Yitzak",
    "Yong-Sun, Harmonist",
    "Yong-Sun, Harmonist (ADV)",
    "Yorik",
    "Ysador the Foul",
    "Yseult",
    "Yuri Kerezenski",
    "Yuri, The Talon",
    "Yusuf, Scribe of Alamut",
    "Yvette, The Hopeless",
    "Zachary",
    "Zack North",
    "Zack North (ADV)",
    "Zahir, Hand of the Silsila",
    "Zane",
    "Zayyat, The Sandstorm",
    "Zebulon",
    "Zelios",
    "Zhara",
    "Zhenga",
    "Zip",
    "Zizi",
    "Zubeida",
    "Zygodat",
    "Zöe",
    "Ági",
    "Étienne Fauberge"
  ]
  
  
  export default krcgCrypt